### PR TITLE
Job services updates

### PR DESCRIPTION
**Pull request by cristianonicolai**
Renamed ExecutorServiceEntryPoint to ExecutorService
Removed unused service methods
Restored Job settings popup

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@mswiderski @nmirasch please review.

**Comment by mswiderski** [comment]
I don't think it makes sense to have the job settings popup there any more as there is not way to support remote stop/start of the executor service at the moment. Moreover not sure we should have this either... though subject for discussion.

**Comment by cristianonicolai** [comment]
@mswiderski I wanted to bring that up for us to either keep if we intend to have that capability to manage executors or remove it completely ( deleting unused methods and JobSettings poup ) if there is no intention to keep this feature. 
Although we could consider that changing these settings should be done at the kie-server level via system properties only, not exposing through the client API, I'm afraid we would be dropping a feature that some might find relevant.
If you think that this sort of settings should be encapsulated in the kie-server itself only, not allowing changes during the server execution, I'm happy to go ahead and remove the settings related code that is left.

**Comment by mswiderski** [comment]
this feature has number of flaws that where never fixed and never reported so in my eyes it's rather rarely used if at all. For instance when you use per process instance strategy and the stop/start executor service it does not properly reset the instance causing all async operations to fail. So I'd prefer to have this as server startup option rather than runtime operation.

**Comment by cristianonicolai** [comment]
@mswiderski agreed. I've updated this PR removing the settings related code.

**Pull request merged**
